-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 21:55:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vuelos` ;

-- -----------------------------------------------------
-- Schema vuelos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vuelos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `vuelos` ;

-- -----------------------------------------------------
-- Table `vuelos`.`tb_ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`tb_ciudad` (
  `codigo_postal` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`codigo_postal`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`tb_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`tb_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATETIME NOT NULL,
  `monto_total` DOUBLE NOT NULL,
  `nombre_comprador` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `vuelos`.`tb_detalle_venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vuelos`.`tb_detalle_venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `fecha_retorno` DATETIME NOT NULL,
  `fecha_viaje` DATETIME NOT NULL,
  `sub_total` DOUBLE NOT NULL,
  `codigo_postal_destino` VARCHAR(50) NULL DEFAULT NULL,
  `codigo_postal_origen` VARCHAR(50) NULL DEFAULT NULL,
  `id_venta` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `FK3ho536egspafe8dyxq5rakl9h`
    FOREIGN KEY (`id_venta`)
    REFERENCES `vuelos`.`tb_venta` (`id`),
  CONSTRAINT `FK66ghk4e0ryd3ec7iv83lpyw5g`
    FOREIGN KEY (`codigo_postal_origen`)
    REFERENCES `vuelos`.`tb_ciudad` (`codigo_postal`),
  CONSTRAINT `FKdu5qxcs6fjg68bu9vmcemkobk`
    FOREIGN KEY (`codigo_postal_destino`)
    REFERENCES `vuelos`.`tb_ciudad` (`codigo_postal`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `FKdu5qxcs6fjg68bu9vmcemkobk` ON `vuelos`.`tb_detalle_venta` (`codigo_postal_destino` ASC) VISIBLE;

CREATE INDEX `FK66ghk4e0ryd3ec7iv83lpyw5g` ON `vuelos`.`tb_detalle_venta` (`codigo_postal_origen` ASC) VISIBLE;

CREATE INDEX `FK3ho536egspafe8dyxq5rakl9h` ON `vuelos`.`tb_detalle_venta` (`id_venta` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use vuelos;
select * from tb_ciudad;
select * from tb_detalle_venta;
select * from tb_venta;

INSERT INTO tb_ciudad (codigo_postal, nombre) VALUES 
('CP001', 'Lima'),
('CP002', 'Arequipa'),
('CP003', 'Cusco'),
('CP004', 'Trujillo');
